### PR TITLE
maplist examples

### PR DESCRIPTION
**Pull request by borisvassilev**
Basic examples for maplist

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks.   Does raise a little question on how to handle `# header`.  The first level-1 section header is used as the title.  I think that is fine.  I'd be tempted to either not use sections for the different examples or to reserve e.g. sections at level 2 (`##`) to act as segments in an example.   What do you think?

**Comment by borisvassilev** [comment]
Hi, I have no opinion on the matter. It would be nice to have segments in examples, with descriptive names. Last I looked (some days ago) only the headers were visible and had to be clicked to expand to see the example, I assumed it is still like this.

Using level 2 header with `##` is a good idea. Then an example either will have no headers, or several sections with `## Descriptive name`.

**Comment by JanWielemaker** [comment]
Looks better now.   Note that the examples provided by a file with the name matching the predicate are open by default.   Collapsed examples come from other examples that mention or use the predicate.   Of course, nothing is fixed (yet).   Thanks for the examples :+1:

**Comment by borisvassilev** [comment]
Now I understand what happens. This is still suboptimal, the whole bunch of examples shows up under length/2, between/3, atom_chars/2 as well. Should I split these "sections" into separate files; would that help?

**Comment by JanWielemaker** [comment]
The example is (I think) fine.   What needs to be fine tuned is the presentation.    The fact that the example was opened and had no title in  length/2 etc., was unintended.   Pushed some fixes for that.

Fine?  Well, maybe it is indeed better to multiple smaller examples with a proper title such that they will show up in the relevant locations, e.g.

```
# Use maplist/2 to test list for integers in a range

?- maplist(between(1, 3), [1, 2, 3]).
true.

?- maplist(between(1, 3), [1, 2, 99]).
false.
```

On the other hand we can argue to put more effort in establishing the proper rules to get the appropriate examples displayed in the best order.   Feel free to experiment.  I'm happy to give you access to the examples repo.  You can then immediately see the result on eu.swi-prolog.org.

**Comment by borisvassilev** [comment]
Yes, you can give me access to the examples repo. Do you need something from me?

Just to make sure I understand: now the idea is to try and split every example _in a separate file_; this way, an example with two predicates (maplist, between/3) only ends up in two places and not all over the place. I will do that with the maplist examples.

**Comment by JanWielemaker** [comment]
> Do you need something from me?

I sent an invite to the documentation team.  That should give you write access.

> Just to make sure I understand

I guess so.  I think you could argue to have one or two basic examples in a file named after the predicate.  Such examples are displayed first and visible immediately.

Anyway, just play with it.   See whether you like it and if not, both consider changing the example repo as well as change the rules on what should be visible and how it should be displayed.

**Pull request merged**
